import { useLayoutEffect, useRef } from 'react';
import type { CSSProperties } from 'react';
import history from './data/gitHistory.json';

// Scene 12 evidence: this deck's own Git history (src/data/gitHistory.json, generated by scripts/git-history.mjs).
// Every number on screen comes from `git log`; nothing is estimated. The choreography is CSS under
// [data-motion="step"] plus a count-up that always lands on the final value when cancelled.

const width = 1200;
const height = 250;
const pad = { left: 40, right: 40, top: 58, bottom: 34 };
const time = (iso: string) => new Date(iso).getTime();
const start = time(history.first ?? history.commits[0].date);
const end = time(history.last ?? history.commits.at(-1)!.date);
const maxLines = Math.max(...history.commits.map((commit) => commit.lines), 1);
const x = (iso: string) => pad.left + ((time(iso) - start) / Math.max(1, end - start)) * (width - pad.left - pad.right);
const y = (lines: number) => height - pad.bottom - (Math.max(0, lines) / maxLines) * (height - pad.top - pad.bottom);
const share = (iso: string) => (time(iso) - start) / Math.max(1, end - start);

const points = history.commits.map((commit) => ({ ...commit, cx: x(commit.date), cy: y(commit.lines), t: share(commit.date) }));
const line = points.map((point, index) => `${index ? 'L' : 'M'}${point.cx.toFixed(1)} ${point.cy.toFixed(1)}`).join(' ');
const area = `${line} L${points.at(-1)!.cx.toFixed(1)} ${height - pad.bottom} L${points[0].cx.toFixed(1)} ${height - pad.bottom} Z`;

// Day ticks at each local midnight inside the history.
const days: string[] = [];
const tick = new Date(start);
tick.setHours(24, 0, 0, 0);
for (; tick.getTime() <= end; tick.setDate(tick.getDate() + 1)) days.push(tick.toISOString());
const dayLabel = (iso: string) => new Date(iso).toLocaleDateString('tr-TR', { day: 'numeric', month: 'short' });
const number = (value: number) => value.toLocaleString('tr-TR');

const counters = [
  { label: 'commit', value: history.totals.commits },
  { label: 'eklenen satır', value: history.totals.insertions },
  { label: 'dosya', value: history.totals.files },
  { label: 'gün', value: Math.max(1, Math.round((end - start) / 86_400_000)) },
];

/** Counts the rendered numbers up from zero once; cancelling or finishing restores the exact final text. */
function useCountUp(animate: boolean) {
  const ref = useRef<HTMLDListElement | null>(null);
  useLayoutEffect(() => {
    const cells = [...(ref.current?.querySelectorAll<HTMLElement>('[data-count]') ?? [])];
    if (!animate || !cells.length) return;
    const finals = cells.map((cell) => cell.textContent ?? '');
    const targets = cells.map((cell) => Number(cell.dataset.count));
    const begin = performance.now();
    let frame = 0;
    const tick = (now: number) => {
      const progress = Math.min(1, (now - begin) / 700);
      const eased = 1 - (1 - progress) ** 3;
      cells.forEach((cell, index) => { cell.textContent = number(Math.round(targets[index] * eased)); });
      if (progress < 1) frame = requestAnimationFrame(tick);
      else cells.forEach((cell, index) => { cell.textContent = finals[index]; });
    };
    frame = requestAnimationFrame(tick);
    return () => {
      cancelAnimationFrame(frame);
      cells.forEach((cell, index) => { cell.textContent = finals[index]; });
    };
  }, [animate]);
  return ref;
}

export default function GitEvidence({ animate }: { animate: boolean }) {
  const countersRef = useCountUp(animate);
  const range = `${dayLabel(history.first ?? '')} – ${dayLabel(history.last ?? '')}`;
  const coAuthored = points.filter((point) => point.coAuthors.length).length;

  return (
    <section className="git-evidence" data-motion-skip aria-label={`Bu sunumun Git kaydı: ${range} arasında ${history.totals.commits} commit, ${history.totals.insertions} eklenen satır, ${history.totals.files} dosya. Dönüm noktaları: ${history.milestones.map((milestone) => milestone.name).join(', ')}.`}>
      <header className="git-evidence-head">
        <span className="git-evidence-kicker">KANIT · BU SUNUMUN GİT KAYDI</span>
        <span className="git-evidence-range">{range} · git log</span>
      </header>
      <dl className="git-evidence-counters" ref={countersRef}>
        {counters.map(({ label, value }, index) => (
          <div key={label} style={{ '--i': index } as CSSProperties}>
            <dt>{label}</dt>
            <dd data-count={value}>{number(value)}</dd>
          </div>
        ))}
      </dl>
      <svg className="git-evidence-timeline" viewBox={`0 0 ${width} ${height}`} aria-hidden="true">
        {days.map((day) => (
          <g key={day} className="git-evidence-day">
            <path d={`M${x(day)} ${pad.top - 10} V${height - pad.bottom}`} />
            <text x={x(day) + 6} y={height - 10}>{dayLabel(day)}</text>
          </g>
        ))}
        <path className="git-evidence-area" d={area} />
        <path className="git-evidence-line" d={line} pathLength={1} />
        {points.map((point) => (
          <circle
            key={point.sha}
            className={`git-evidence-commit${point.coAuthors.length ? ' is-coauthored' : ''}`}
            cx={point.cx}
            cy={point.cy}
            r={point.coAuthors.length ? 7 : 4.5}
            style={{ '--t': point.t } as CSSProperties}
          />
        ))}
        {history.milestones.map((milestone, index) => {
          const point = points.find((item) => item.sha === milestone.sha);
          if (!point) return null;
          // Milestones can fall on the same day: each gets its own label row.
          const labelY = pad.top - 8 - (history.milestones.length - 1 - index) * 24;
          const anchor = point.t > 0.85 ? 'end' : 'start';
          const labelX = anchor === 'end' ? point.cx - 10 : point.cx + 10;
          return (
            <g key={milestone.name} className="git-evidence-milestone" style={{ '--t': point.t } as CSSProperties}>
              <path d={`M${point.cx} ${labelY - 14} V${point.cy}`} />
              <text x={labelX} y={labelY} textAnchor={anchor}>{milestone.name}</text>
            </g>
          );
        })}
      </svg>
      <p className="git-evidence-legend">
        <span><i className="is-commit" /> commit · biriken satır</span>
        <span><i className="is-coauthored" /> ajanın ortak yazar olduğu commit ({coAuthored})</span>
        <span>Bütün commit'ler insan onayıyla</span>
      </p>
      <div className="git-evidence-diffs">
        {history.snippets.map((snippet) => (
          <figure key={snippet.sha + snippet.file}>
            <figcaption><code>{snippet.sha}</code> {snippet.file} <span>· {snippet.note}</span></figcaption>
            <pre>
              {snippet.lines.map((text, index) => (
                <code key={index} className={text.startsWith('+') ? 'is-add' : text.startsWith('-') ? 'is-del' : undefined} style={{ '--i': index } as CSSProperties}>{text || ' '}</code>
              ))}
            </pre>
          </figure>
        ))}
      </div>
    </section>
  );
}
